name: Deploy Static

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}

      - name: Pull from github
        run: ssh server 'cd /repo/under-construction-template && git pull'

      - name: Install dependencies
        run: ssh server 'cd /repo/under-construction-template && npm install'

      - name: Build project
        run: ssh server 'cd /repo/under-construction-template && npm run build'

      - name: Clean deploy folder
        run: ssh server 'rm -r /var/www/under-construction/*'

      - name: Copy files to deploy folder
        run: ssh server 'cp -r /repo/under-construction-template/dist/. /var/www/under-construction/'
